@baseUrl = http://localhost:3000/api
@token = 

###

POST {{baseUrl}}/products HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "Description": "Teste",
    "UnitPrice": 5,
    "Amount": 1000
}

###

GET {{baseUrl}}/products HTTP/1.1
Authorization: {{token}}

###

GET {{baseUrl}}/products/636f7126-b77f-43b9-9888-866cf192737c HTTP/1.1
Authorization: {{token}}

###

DELETE {{baseUrl}}/products/d025d8eb-016d-4720-b4bb-803dd77a7e24 HTTP/1.1
Authorization: {{token}}

###

PUT {{baseUrl}}/products HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "Id": "42e06024-10ef-4cf8-869b-a85f16589c54",
    "Description": "Prego Pequeno",
    "UnitPrice": 1,
    "Amount": 1000
}

###

POST {{baseUrl}}/sells HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "SellProducts": [
        {
            "ProductId": "7d8aa35c-a8d7-4fae-9630-67f87e9951e2",
            "Amount": 20,
            "UnitPrice": 1
        },
        {
            "ProductId": "58230986-c5fb-472e-bd20-a0b6b8b87cfb",
            "Amount": 1,
            "UnitPrice": 15
        },
        {
            "ProductId": "278e0c0a-8264-43c0-bda4-4c94f795a999",
            "Amount": 1,
            "UnitPrice": 10
        }
    ]
}

###

GET {{baseUrl}}/sells HTTP/1.1
Authorization: {{token}}

###

POST {{baseUrl}}/auth HTTP/1.1
Content-Type: application/json

{
    "Email": "contato@contato.com",
    "Password": "123456"
}

###

POST {{baseUrl}}/users HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "Email": "contato@contato.com",
    "Password": "123456",
    "Name": "Contato A"
}