@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/products HTTP/1.1
Content-Type: application/json

{
    "description": "Alicate",
    "unitPrice": 15,
    "amount": 50
}

###

GET {{baseUrl}}/products HTTP/1.1

###

GET {{baseUrl}}/products/fa16bc3c-6763-487d-805e-7084aaef2e95 HTTP/1.1

###

DELETE {{baseUrl}}/products/fa16bc3c-6763-487d-805e-7084aaef2e95 HTTP/1.1

###

PUT {{baseUrl}}/products HTTP/1.1
Content-Type: application/json

{
    "id": "e9a6e8ef-5fbb-428b-931d-599d7ec8d44b",
    "description": "Parafuso",
    "unitPrice": 1.50,
    "amount": 500
}

###

POST {{baseUrl}}/sells HTTP/1.1
Content-Type: application/json

{
    "sellProducts": [
        {
            "productId": "7d8aa35c-a8d7-4fae-9630-67f87e9951e2",
            "amount": 5,
            "unitPrice": 1
        },
        {
            "productId": "58230986-c5fb-472e-bd20-a0b6b8b87cfb",
            "amount": 1,
            "unitPrice": 15
        }
    ]
}
